import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { useParams, useNavigate } from 'react-router-dom';
import { useAccount } from 'wagmi';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Navbar } from '@/components/Navbar';
import { AgentService } from '@/services/agentService';
import { SignalService } from '@/services/signalService';
import { IntegrationService } from '@/services/integrationService';
import type { Database } from '@/integrations/supabase/types';
import { toast } from 'sonner';
import { 
  ArrowLeft, 
  Play, 
  Pause, 
  TrendingUp, 
  TrendingDown,
  Activity,
  Clock,
  ExternalLink,
  Settings,
  AlertCircle,
  RefreshCw,
  Zap
} from 'lucide-react';

type Agent = Database['public']['Tables']['agents']['Row'];
type TradingSignal = Database['public']['Tables']['trading_signals']['Row'];

const AgentDetails = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { isConnected, address } = useAccount();
  
  const [agent, setAgent] = useState<Agent | null>(null);
  const [signals, setSignals] = useState<TradingSignal[]>([]);
  const [loading, setLoading] = useState(true);
  const [updating, setUpdating] = useState(false);
  const [generatingSignal, setGeneratingSignal] = useState(false);
  const [blockchainData, setBlockchainData] = useState<any>(null);
  const [marketAnalysis, setMarketAnalysis] = useState<any>(null);

  useEffect(() => {
    if (isConnected && id) {
      loadAgentData();
    }
  }, [isConnected, id]);

  const loadAgentData = async () => {
    if (!id) return;
    
    try {
      setLoading(true);
      // Use comprehensive data fetching with blockchain and AI integration
      const comprehensiveData = await AgentService.getComprehensiveAgentData(id);
      
      if (!comprehensiveData.agent) {
        toast.error('Agent not found');
        navigate('/dashboard');
        return;
      }
      
      setAgent(comprehensiveData.agent);
      setSignals(comprehensiveData.signals);
      setBlockchainData(comprehensiveData.blockchainData);
      setMarketAnalysis(comprehensiveData.marketAnalysis);
      
      if (comprehensiveData.isBlockchainSynced) {
        console.log('✅ Agent is synced with blockchain');
      } else {
        console.log('⚠️ Agent not synced with blockchain');
      }
    } catch (error) {
      console.error('Failed to load agent data:', error);
      toast.error('Failed to load agent data');
    } finally {
      setLoading(false);
    }
  };

  const handleToggleAgent = async () => {
    if (!agent || !address) return;
    
    const newStatus = agent.status === 'active' ? 'paused' : 'active';
    
    try {
      setUpdating(true);
      // Use integrated service for blockchain sync
      const result = await AgentService.updateAgentStatusWithSync(agent.id, newStatus, address);
      
      setAgent({ ...agent, status: newStatus });
      
      if (result.blockchainTxHash) {
        toast.success(`Agent ${newStatus === 'active' ? 'resumed' : 'paused'} and synced with blockchain! 🚀`);
      } else {
        toast.success(`Agent ${newStatus === 'active' ? 'resumed' : 'paused'} in database. Blockchain sync can be done later.`);
      }
    } catch (error) {
      console.error('Failed to update agent status:', error);
      toast.error('Failed to update agent status');
    } finally {
      setUpdating(false);
    }
  };

  const handleGenerateSignal = async () => {
    if (!agent || !address) return;
    
    try {
      setGeneratingSignal(true);
      // Use integrated service for AI + optional blockchain execution
      const result = await IntegrationService.generateAndExecuteSignal(
        agent.id, 
        address, 
        false // Don't auto-execute on blockchain by default
      );
      
      setSignals([result.signal, ...signals]);
      
      if (result.executionTxHash) {
        toast.success(`${result.signal.signal_type} signal generated and executed on blockchain! 🚀`);
      } else {
        toast.success(`${result.signal.signal_type} signal generated by AI`);
      }
    } catch (error) {
      console.error('Failed to generate signal:', error);
      toast.error('Failed to generate signal');
    } finally {
      setGeneratingSignal(false);
    }
  };

  const strategyNames = {
    trend: 'Trend Following',
    momentum: 'Momentum',
    'mean-reversion': 'Mean Reversion'
  };

  if (!isConnected) {
    return (
      <div className="min-h-screen bg-background">
        <Navbar />
        <div className="container mx-auto px-4 pt-32">
          <div className="text-center">
            <h1 className="text-3xl font-bold mb-4">Connect Your Wallet</h1>
            <p className="text-muted-foreground mb-8">Connect your wallet to view agent details</p>
          </div>
        </div>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-background">
        <Navbar />
        <div className="container mx-auto px-4 pt-32">
          <div className="flex items-center justify-center">
            <div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin" />
          </div>
        </div>
      </div>
    );
  }

  if (!agent) {
    return (
      <div className="min-h-screen bg-background">
        <Navbar />
        <div className="container mx-auto px-4 pt-32">
          <div className="text-center">
            <h1 className="text-3xl font-bold mb-4">Agent Not Found</h1>
            <Button onClick={() => navigate('/dashboard')}>
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Dashboard
            </Button>
          </div>
        </div>
      </div>
    );
  }

  const pnlPercent = agent.allocated_amount > 0 ? (agent.total_pnl / agent.allocated_amount) * 100 : 0;

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      
      <div className="container mx-auto px-4 pt-24 pb-12">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div className="flex items-center gap-4">
            <Button 
              variant="ghost" 
              size="sm" 
              onClick={() => navigate('/dashboard')}
              className="hover:bg-secondary"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Dashboard
            </Button>
          </div>
          <div className="flex gap-3">
            <Button 
              variant="outline" 
              size="sm"
              onClick={handleGenerateSignal}
              disabled={generatingSignal || agent.status !== 'active'}
            >
              <Zap className={`w-4 h-4 mr-2 ${generatingSignal ? 'animate-pulse' : ''}`} />
              Generate Signal
            </Button>
            <Button 
              onClick={handleToggleAgent}
              disabled={updating}
              variant={agent.status === 'active' ? 'destructive' : 'default'}
              size="sm"
            >
              {updating ? (
                <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
              ) : agent.status === 'active' ? (
                <>
                  <Pause className="w-4 h-4 mr-2" />
                  Pause Agent
                </>
              ) : (
                <>
                  <Play className="w-4 h-4 mr-2" />
                  Resume Agent
                </>
              )}
            </Button>
          </div>
        </div>

        {/* Agent Overview */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
          <div className="lg:col-span-2">
            <Card className="glass-card">
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle className="text-2xl">{agent.name}</CardTitle>
                    <p className="text-muted-foreground">{strategyNames[agent.strategy]}</p>
                  </div>
                  <Badge 
                    variant={agent.status === 'active' ? 'default' : 'secondary'}
                    className={agent.status === 'active' ? 'bg-neon-green/20 text-neon-green' : ''}
                  >
                    {agent.status === 'active' ? <Play className="w-3 h-3 mr-1" /> : <Pause className="w-3 h-3 mr-1" />}
                    {agent.status}
                  </Badge>
                </div>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Current Balance</p>
                    <p className="text-2xl font-bold">${agent.current_balance.toLocaleString()}</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Total P&L</p>
                    <p className={`text-2xl font-bold ${agent.total_pnl >= 0 ? 'text-neon-green' : 'text-red-400'}`}>
                      {agent.total_pnl >= 0 ? '+' : ''}${agent.total_pnl.toFixed(2)}
                    </p>
                    <p className={`text-sm ${agent.total_pnl >= 0 ? 'text-neon-green' : 'text-red-400'}`}>
                      {pnlPercent >= 0 ? '+' : ''}{pnlPercent.toFixed(1)}%
                    </p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Total Trades</p>
                    <p className="text-2xl font-bold">{agent.total_trades}</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Win Rate</p>
                    <p className="text-2xl font-bold">{agent.win_rate}%</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          <div className="space-y-4">
            <Card className="glass-card">
              <CardHeader className="pb-3">
                <CardTitle className="text-lg">Agent Info</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Risk Level</span>
                  <span className="font-medium capitalize">{agent.risk_level}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Created</span>
                  <span className="font-medium">{new Date(agent.created_at).toLocaleDateString()}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Last Signal</span>
                  <span className="font-medium">
                    {agent.last_signal_at 
                      ? new Date(agent.last_signal_at).toLocaleString()
                      : 'Never'
                    }
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Allocated Amount</span>
                  <span className="font-medium">${agent.allocated_amount.toLocaleString()}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Slippage Tolerance</span>
                  <span className="font-medium">{agent.slippage_tolerance}%</span>
                </div>
              </CardContent>
            </Card>

            {agent.status === 'paused' && (
              <Card className="glass-card border-yellow-500/20">
                <CardContent className="p-4">
                  <div className="flex items-start gap-3">
                    <AlertCircle className="w-5 h-5 text-yellow-500 mt-0.5" />
                    <div>
                      <p className="font-medium text-yellow-500 mb-1">Agent Paused</p>
                      <p className="text-sm text-muted-foreground">
                        This agent is currently paused and not executing trades.
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            )}
          </div>
        </div>

        {/* Tabs */}
        <Tabs defaultValue="signals" className="space-y-6">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="signals">Trading Signals</TabsTrigger>
            <TabsTrigger value="pairs">Token Pairs</TabsTrigger>
            <TabsTrigger value="strategy">Strategy Details</TabsTrigger>
          </TabsList>

          <TabsContent value="signals">
            <Card className="glass-card">
              <CardHeader>
                <CardTitle>Recent Signals</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {signals.length === 0 ? (
                    <div className="text-center py-8">
                      <Activity className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
                      <p className="text-muted-foreground">No signals generated yet</p>
                      {agent.status === 'active' && (
                        <Button 
                          onClick={handleGenerateSignal}
                          disabled={generatingSignal}
                          className="mt-4"
                        >
                          <Zap className="w-4 h-4 mr-2" />
                          Generate First Signal
                        </Button>
                      )}
                    </div>
                  ) : (
                    signals.map((signal, index) => (
                      <motion.div
                        key={`${signal.id}-${index}`}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="flex items-center justify-between p-4 rounded-lg border border-border/50 hover:border-border transition-colors"
                      >
                        <div className="flex items-center gap-4">
                          <div className={`w-8 h-8 rounded-full flex items-center justify-center ${
                            signal.signal_type === 'BUY' 
                              ? 'bg-neon-green/20 text-neon-green' 
                              : signal.signal_type === 'SELL'
                              ? 'bg-red-400/20 text-red-400'
                              : 'bg-yellow-400/20 text-yellow-400'
                          }`}>
                            {signal.signal_type === 'BUY' ? (
                              <TrendingUp className="w-4 h-4" />
                            ) : signal.signal_type === 'SELL' ? (
                              <TrendingDown className="w-4 h-4" />
                            ) : (
                              <Activity className="w-4 h-4" />
                            )}
                          </div>
                          <div>
                            <p className="font-medium">{signal.token_pair}</p>
                            <p className="text-sm text-muted-foreground">
                              {signal.signal_type} • Confidence: {signal.confidence_score}%
                            </p>
                            <p className="text-xs text-muted-foreground mt-1">
                              {signal.reasoning}
                            </p>
                          </div>
                        </div>
                        <div className="text-right">
                          <Badge variant={signal.executed ? 'default' : 'secondary'}>
                            {signal.executed ? 'Executed' : 'Pending'}
                          </Badge>
                          <div className="flex items-center gap-2 text-sm text-muted-foreground mt-1">
                            <Clock className="w-3 h-3" />
                            {new Date(signal.created_at).toLocaleString()}
                            {signal.transaction_hash && (
                              <Button variant="ghost" size="sm" className="h-auto p-0 ml-2">
                                <ExternalLink className="w-3 h-3" />
                              </Button>
                            )}
                          </div>
                        </div>
                      </motion.div>
                    ))
                  )}
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="pairs">
            <Card className="glass-card">
              <CardHeader>
                <CardTitle>Trading Pairs</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                  {agent.token_pairs.map((pair) => (
                    <div key={pair} className="p-4 rounded-lg border border-border/50">
                      <p className="font-medium">{pair}</p>
                      <p className="text-sm text-muted-foreground">Active</p>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="strategy">
            <Card className="glass-card">
              <CardHeader>
                <CardTitle>Strategy Configuration</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-6">
                  <div>
                    <h3 className="font-semibold mb-2">{strategyNames[agent.strategy]} Strategy</h3>
                    <p className="text-muted-foreground mb-4">
                      {agent.strategy === 'trend' && 'This agent follows market trends and momentum indicators to make trading decisions.'}
                      {agent.strategy === 'momentum' && 'This agent captures short-term price movements and momentum shifts.'}
                      {agent.strategy === 'mean-reversion' && 'This agent identifies overbought/oversold conditions and trades reversals.'}
                    </p>
                  </div>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div>
                      <h4 className="font-medium mb-3">Risk Management</h4>
                      <div className="space-y-2">
                        <div className="flex justify-between">
                          <span className="text-muted-foreground">Risk Level</span>
                          <span className="capitalize">{agent.risk_level}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-muted-foreground">Slippage Tolerance</span>
                          <span>{agent.slippage_tolerance}%</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-muted-foreground">Max Position Size</span>
                          <span>
                            {agent.risk_level === 'low' ? '10%' : 
                             agent.risk_level === 'medium' ? '25%' : '40%'}
                          </span>
                        </div>
                      </div>
                    </div>
                    
                    <div>
                      <h4 className="font-medium mb-3">Gas Settings</h4>
                      <div className="space-y-2">
                        <div className="flex justify-between">
                          <span className="text-muted-foreground">Max Fee Per Gas</span>
                          <span>{(agent.gas_settings as any)?.maxFeePerGas || 'Auto'} Gwei</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-muted-foreground">Priority Fee</span>
                          <span>{(agent.gas_settings as any)?.maxPriorityFeePerGas || 'Auto'} Gwei</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
};

export default AgentDetails;